
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async saveImagesBatch(images: ImageRecord[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_images_batch", { images }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDbDiagnostics() : Promise<Result<DbDiagnostics, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshBoardsNative(boardMapping: Partial<{ [key in string]: string }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_boards_native", { boardMapping }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImageCountForPathPrefix(path: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_image_count_for_path_prefix", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async optimizeDatabase() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request a database purge on next app startup.
 * Creates a marker file and immediately restarts the application.
 */
async purgeDatabase() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get parameter ranges and distinct values for dynamic filter UI.
 * Only returns non-null/non-default values to show what data actually exists.
 */
async getParameterRanges(whereClause: string | null, paramsJson: string | null, collectionId: string | null, loraName: string | null) : Promise<Result<ParameterRanges, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_parameter_ranges", { whereClause, paramsJson, collectionId, loraName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Backfill the denormalized parameter columns (steps, cfg, sampler, generation_type).
 * This runs in batches to avoid blocking the database and can be called after app startup.
 * Returns the number of rows updated.
 */
async backfillParameterColumns() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backfill_parameter_columns") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildFacetCache() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_facet_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get distinct facet names that exist in the current filtered result set.
 * This is used for drill-down filtering - hiding facets that have no images
 * in the current filter context.
 * 
 * OPTIMIZATION: Uses a single UNION ALL query instead of 5 separate queries
 * to reduce database round-trips and allow SQLite to share table scans.
 */
async getValidFacetNames(whereClause: string, paramsJson: string, collectionId: string | null, loraName: string | null) : Promise<Result<ValidFacetNames, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_valid_facet_names", { whereClause, paramsJson, collectionId, loraName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a batch of images as corrupt to prevent further processing attempts.
 * This clears any partial thumbnail data and sets is_corrupt = 1.
 */
async markImagesCorrupt(ids: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_images_corrupt", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyLibraryIntegrity() : Promise<Result<IntegrityResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_library_integrity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get count and batch of images needing metadata re-parsing.
 * Returns images where parser_version < CURRENT_PARSER_VERSION.
 */
async getImagesNeedingReparse(limit: number | null) : Promise<Result<ImageToReparse[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_images_needing_reparse", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get count of images needing re-parsing (for progress display).
 */
async getReparseCount() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_reparse_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-parse a batch of images from their stored original_metadata_json.
 * Updates metadata_json, denormalized columns, and parser_version.
 */
async reparseMetadataBatch(images: ImageToReparse[]) : Promise<Result<ReparseBatchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reparse_metadata_batch", { images }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force re-parse all images by resetting parser_version to 0.
 * Dev tool for testing parser improvements.
 */
async resetParserVersions() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_parser_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBackups() : Promise<Result<BackupInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backupDatabase() : Promise<Result<BackupInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if we need to run an auto-backup (first run of the day).
 */
async checkAndRunAutobackup() : Promise<Result<BackupInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_and_run_autobackup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanImage(path: string, thumbnailDir: string | null, skipThumbnail: boolean, extractWorkflow: boolean, defaultTool: string | null) : Promise<Result<ScanResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_image", { path, thumbnailDir, skipThumbnail, extractWorkflow, defaultTool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanImagesBulk(paths: string[], thumbnailDir: string | null, skipThumbnail: boolean, extractWorkflow: boolean, defaultTool: string | null) : Promise<Result<ScanResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_images_bulk", { paths, thumbnailDir, skipThumbnail, extractWorkflow, defaultTool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanImageWorkflow(path: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_image_workflow", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readImageMetadata(path: string, defaultTool: string | null) : Promise<Result<ImageMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_image_metadata", { path, defaultTool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileSizesBulk(paths: string[]) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_sizes_bulk", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyImagePaths(paths: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_image_paths", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async auditInvokeaiFolder(path: string) : Promise<Result<FolderStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audit_invokeai_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInvokeaiImages(path: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_invokeai_images", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanDirectoryRecursive(path: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_directory_recursive", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showInFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_in_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanDirectoryWithStats(path: string) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_directory_with_stats", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanDirectorySince(path: string, since: number) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_directory_since", { path, since }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startNativeFolderWatcher(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_native_folder_watcher", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importA1111Cache(cachePath: string) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_a1111_cache", { cachePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveHashesOnline(skipHarvest: boolean) : Promise<Result<ResolutionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_hashes_online", { skipHarvest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearModelCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_model_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelModelResolution() : Promise<void> {
    await TAURI_INVOKE("cancel_model_resolution");
},
async cancelModelDiscovery() : Promise<void> {
    await TAURI_INVOKE("cancel_model_discovery");
},
async scanModelThumbnails(paths: string[]) : Promise<Result<ThumbnailScanResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_model_thumbnails", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelThumbnail(modelHash: string, modelName: string | null, imagePath: string, resourceType: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_thumbnail", { modelHash, modelName, imagePath, resourceType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsetModelThumbnail(modelHash: string, modelName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unset_model_thumbnail", { modelHash, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllThumbnails(modelHash: string, modelName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_thumbnails", { modelHash, modelName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveToTrash(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_to_trash", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteThumbnail(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_thumbnail", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BackupInfo = { name: string; path: string; createdAt: string; sizeBytes: number }
export type DbDiagnostics = { dbPath: string; imageCount: number; deletedCount: number; modelCount: number; cacheCount: number; toolNullCount: number }
export type FileEntry = { path: string; modified: number; size: number }
export type FolderStats = { totalFiles: number; imageFiles: number; thumbnailFiles: number; otherFiles: number; directoryChecked: string; subfolders: Partial<{ [key in string]: number }> }
export type ImageMetadata = { tool: string; model: string; rawParameters?: string | null; steps: number; cfg: number; seed: number; sampler: string; positivePrompt: string; negativePrompt: string; loras: string[]; controlNets: string[]; ipAdapters: string[]; embeddings: string[]; hypernetworks: string[]; variationId?: string | null; isIntermediate?: boolean; isGrid?: boolean; workflowJson?: string | null; vae?: string | null; clipSkip?: number | null; denoisingStrength?: number | null; hiresUpscale?: number | null; hiresSteps?: number | null; hiresUpscaler?: string | null; modelHash?: string | null; generationType: string; isFavorite?: boolean }
export type ImageRecord = { id: string; path: string; width: number; height: number; fileSize: number; timestamp: number; metadataJson: string; thumbnailPath: string; 
/**
 * Base64 encoded 32px WebP micro-thumbnail for instant previews
 */
microThumbnail: string | null; 
/**
 * Source of the thumbnail: 'ambit', 'invokeai', etc.
 */
thumbnailSource: string | null; isFavorite: boolean; isPinned: boolean; isDeleted: boolean; isMissing: boolean; isCorrupt: boolean; userMasked: boolean | null; groupId: string | null; boardId: string | null; notes: string | null; originalMetadataJson: string | null; originalStateJson: string | null }
/**
 * Image needing re-parse: minimal data for efficient batch processing.
 */
export type ImageToReparse = { id: string; tool: string; originalMetadataJson: string }
export type ImportResult = { added: number; totalFound: number; message: string }
/**
 * Verify integrity of the entire library.
 * 1. Checks if source file exists -> Updates is_missing
 * 2. If source exists, checks if thumbnail exists -> Clears thumbnail_path if missing (triggers regen)
 * Returns (missing_files_count, recovered_files_count, broken_thumbs_count)
 */
export type IntegrityResult = { missing: number; recovered: number; broken_thumbs: number }
/**
 * Numeric range for a parameter
 */
export type NumericRange = { min: number; max: number }
/**
 * Parameter ranges and distinct values for dynamic filters
 */
export type ParameterRanges = { steps: NumericRange | null; cfg: NumericRange | null; denoisingStrength: NumericRange | null; samplers: string[]; generationTypes: string[]; controlNets: string[]; ipAdapters: string[]; guidanceSubtypes: Partial<{ [key in string]: string }> }
/**
 * Result of a batch re-parse operation.
 */
export type ReparseBatchResult = { processed: number; updated: number; errors: number }
export type ResolutionResult = { resolvedCount: number; failedCount: number; namedFallbackCount: number; unknownCount: number }
export type ScanResult = { width: number; height: number; size: number; modified: number; thumbnail: string; 
/**
 * Base64 encoded 32px WebP micro-thumbnail for instant previews
 */
microThumbnail: string | null; 
/**
 * Source of the thumbnail: 'ambit', 'invokeai', etc.
 */
thumbnailSource: string | null; chunks: Partial<{ [key in string]: string }>; metadata: ImageMetadata | null; 
/**
 * Error message if scan failed or resulted in a partial result
 */
error: string | null }
export type ThumbnailScanResult = { found: number; updated: number }
/**
 * Valid facet names result - used for drill-down filtering
 */
export type ValidFacetNames = { checkpoints: string[]; loras: string[]; embeddings: string[]; hypernetworks: string[]; tools: string[]; controlNets: string[]; ipAdapters: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
